[build-system]
requires = ["setuptools>=74", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "uklatn"
dynamic = ["version"]

[tool.setuptools]
package-dir = {"" = "python"}

[tool.setuptools_scm]

