# Generated by gentests.py, do not edit.

defmodule Paiv.UkrainianLatinTest do
  use ExUnit.Case
  doctest Paiv.UkrainianLatin

  test "DSTU_9112_A #1" do
    cyr = "Україна, Хмельницький"
    lat = "Ukraïna, Xmeljnycjkyj"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #2" do
    cyr = "Щастям б’єш жук їх глицю в фон й ґедзь пріч."
    lat = "Ŝastjam b'ješ žuk ïx ğlycju v fon j gedzj prič."
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #3" do
    cyr = "ь Ь ль льє льї лью лья лье льі льу льа льйо льо"
    lat = "ĵ Ĵ lj ljje ljï ljju ljja lj'e lji lj'u lj'a ljjo ljo"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #4" do
    cyr = "Єл Їл Юл Ял"
    lat = "Jel Ïl Jul Jal"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #5" do
    cyr = "бь вь гь ґь дь жь зь кь ль мь нь пь рь сь ть фь хь ць чь шь щь"
    lat = "bj vj ğj gj dj žj zj kj lj mj nj pj rj sj tj fj xj cj čj šj ŝj"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #6" do
    cyr = "бя вя гя ґя дя жя зя кя ля мя ня пя ря ся тя фя хя ця чя шя щя"
    lat = "bja vja ğja gja dja žja zja kja lja mja nja pja rja sja tja fja xja cja čja šja ŝja"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #7" do
    cyr = "б’я в’я г’я ґ’я д’я ж’я з’я к’я л’я м’я н’я п’я р’я с’я т’я ф’я х’я ц’я ч’я ш’я щ’я"

    lat =
      "b'ja v'ja ğ'ja g'ja d'ja ž'ja z'ja k'ja l'ja m'ja n'ja p'ja r'ja s'ja t'ja f'ja x'ja c'ja č'ja š'ja ŝ'ja"

    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #8" do
    cyr = "бй бйо вй гй ґй дй жй зй кй лй мй нй пй рй сй тй фй хй цй чй шй щй"

    lat =
      "b'j b'jo v'j ğ'j g'j d'j ž'j z'j k'j l'j m'j n'j p'j r'j s'j t'j f'j x'j c'j č'j š'j ŝ'j"

    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #9" do
    cyr = "ня ньа н’я нь'н ньн"
    lat = "nja nj'a n'ja nj'n njn"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #10" do
    cyr = "рос дыня эзёдынъ. бр кроў."
    lat = "ros dȳnja ēzödȳnǒ. br kroŭ."
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #11" do
    cyr = "А́ а́ Е́ е́ Є́ є́ И́ и́ І́ і́ Ї́ ї́ О́ о́ У́ у́ Ю́ ю́ Я́ я́"
    lat = "Á á É é JÉ jé Ý ý Í í Ḯ ḯ Ó ó Ú ú JÚ jú JÁ já"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #12" do
    cyr = "Є́с сЄ́с є́с сє́с Ї́с сЇ́с ї́с сї́с Ю́с сЮ́с ю́с сю́с Я́с сЯ́с я́с ся́с"
    lat = "Jés sJés jés sjés Ḯs sḮs ḯs sḯs Jús sJús jús sjús Jás sJás jás sjás"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #13" do
    cyr = "' ім’я 'жук' \"жук\" ' '"
    lat = "' im'ja 'žuk' \"žuk\" ' '"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #14" do
    cyr =
      "Сонце світить майже білим світлом, однак через сильніше розсіювання і поглинання короткохвильової частини спектра атмосферою Землі пряме світло Сонця біля поверхні нашої планети набуває певного жовтого відтінку. Якщо небо ясне, то блакитний відтінок розсіяного світла складається з жовтуватим прямим сонячним світлом і загальне освітлення об’єктів на Землі стає білим."

    lat =
      "Sonce svitytj majže bilym svitlom, odnak čerez syljniše rozsijuvannja i poğlynannja korotkoxvyljovoï častyny spektra atmosferoju Zemli prjame svitlo Soncja bilja poverxni našoï planety nabuvaje pevnoğo žovtoğo vidtinku. Jakŝo nebo jasne, to blakytnyj vidtinok rozsijanoğo svitla skladajetjsja z žovtuvatym prjamym sonjačnym svitlom i zağaljne osvitlennja ob'jektiv na Zemli staje bilym."

    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #22" do
    cyr =
      "дуб!дуб\"дуб#дуб$дуб%дуб&дуб'дуб(дуб)дуб*дуб+дуб,дуб-дуб.дуб/дуб:дуб;дуб<дуб=дуб>дуб?дуб@дуб[дуб\\дуб]дуб^дуб_дуб`дуб{дуб|дуб}дуб~дуб"

    lat =
      "dub!dub\"dub#dub$dub%dub&dub'dub(dub)dub*dub+dub,dub-dub.dub/dub:dub;dub<dub=dub>dub?dub@dub[dub\\dub]dub^dub_dub`dub{dub|dub}dub~dub"

    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #23" do
    cyr = "бод бод\tбод\nбод\rбод"
    lat = "bod bod\tbod\nbod\rbod"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #24" do
    cyr = "об😎нап😘неп😭нєп🧐нїп😍нюп😀няп"
    lat = "ob😎nap😘nep😭njep🧐nïp😍njup😀njap"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.encode(cyr) == lat
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #15" do
    cyr = "в’я в'я"
    lat = "v'ja v'ja"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.encode(cyr) == lat
  end

  test "DSTU_9112_A #16" do
    cyr = "Ї ї Й й Ё ё Ў ў"
    lat = "Ï ï J j Ö ö Ŭ ŭ"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_A) == lat
    assert Paiv.UkrainianLatin.encode(cyr) == lat
  end

  test "DSTU_9112_A #17" do
    cyr = "я є ю"
    lat = "jA jE jU"
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #18" do
    cyr = "Ї ї Ь ь Ч ч Г г Щ щ Ш ш Ж ж"
    lat = "Ï ï Ĵ ĵ Č č Ğ ğ Ŝ ŝ Š š Ž ž"
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #19" do
    cyr = "Ё ё Ў ў Ъ ъ Ы ы Э э"
    lat = "Ö ö Ŭ ŭ Ǒ ǒ Ȳ ȳ Ē ē"
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #20" do
    cyr = "А́ а́ Е́ е́ Є́ Є́ є́ є́ И́ и́ І́ і́ Ї́ ї́ О́ о́ У́ у́ Ю́ Ю́ ю́ ю́ Я́ Я́ я́ я́"
    lat = "Á á É é JÉ Jé jÉ jé Ý ý Í í Ḯ ḯ Ó ó Ú ú JÚ Jú jÚ jú JÁ Já jÁ já"
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_A #21" do
    cyr = "Є́с сЄ́с є́с сє́с Ї́с сЇ́с ї́с сї́с Ю́с сЮ́с ю́с сю́с Я́с сЯ́с я́с ся́с"
    lat = "Jés sJés jés sjés Ḯs sḮs ḯs sḯs Jús sJús jús sjús Jás sJás jás sjás"
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_A) == cyr
    assert Paiv.UkrainianLatin.decode(lat) == cyr
  end

  test "DSTU_9112_B #1" do
    cyr = "Україна, Хмельницький"
    lat = "Ukrajina, Khmeljnycjkyj"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #2" do
    cyr = "Щастям б’єш жук їх глицю в фон й ґедзь пріч."
    lat = "Shchastjam b'jesh zhuk jikh ghlycju v fon j gedzj prich."
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #3" do
    cyr = "ь Ь ль льє льї лью лья лье льі льу льа льйо льо"
    lat = "hj Hj lj ljje ljji ljju ljja lj'e lj'i lj'u lj'a ljjo ljo"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #4" do
    cyr = "Єл Їл Юл Ял"
    lat = "Jel Jil Jul Jal"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #5" do
    cyr = "бь вь гь ґь дь жь зь кь ль мь нь пь рь сь ть фь хь ць чь шь щь"
    lat = "bj vj ghj gj dj zhj zj kj lj mj nj pj rj sj tj fj khj cj chj shj shchj"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #6" do
    cyr = "бя вя гя ґя дя жя зя кя ля мя ня пя ря ся тя фя хя ця чя шя щя"

    lat =
      "bja vja ghja gja dja zhja zja kja lja mja nja pja rja sja tja fja khja cja chja shja shchja"

    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #7" do
    cyr = "б’я в’я г’я ґ’я д’я ж’я з’я к’я л’я м’я н’я п’я р’я с’я т’я ф’я х’я ц’я ч’я ш’я щ’я"

    lat =
      "b'ja v'ja gh'ja g'ja d'ja zh'ja z'ja k'ja l'ja m'ja n'ja p'ja r'ja s'ja t'ja f'ja kh'ja c'ja ch'ja sh'ja shch'ja"

    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #8" do
    cyr = "бй бйо вй гй ґй дй жй зй кй лй мй нй пй рй сй тй фй хй цй чй шй щй"

    lat =
      "b'j b'jo v'j gh'j g'j d'j zh'j z'j k'j l'j m'j n'j p'j r'j s'j t'j f'j kh'j c'j ch'j sh'j shch'j"

    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #9" do
    cyr = "ня ньа н’я нь'н ньн"
    lat = "nja nj'a n'ja nj'n njn"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #10" do
    cyr = "рос дыня эзёдынъ. бр кроў."
    lat = "ros dywnja ehwzjowdywnoh. br krouh."
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #11" do
    cyr = "А́ а́ Е́ е́ Є́ є́ И́ и́ І́ і́ Ї́ ї́ О́ о́ У́ у́ Ю́ ю́ Я́ я́"
    lat = "Á á É é JÉ jé Ý ý Í í JÍ jí Ó ó Ú ú JÚ jú JÁ já"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #12" do
    cyr = "Є́с сЄ́с є́с сє́с Ї́с сЇ́с ї́с сї́с Ю́с сЮ́с ю́с сю́с Я́с сЯ́с я́с ся́с"
    lat = "Jés sJés jés sjés Jís sJís jís sjís Jús sJús jús sjús Jás sJás jás sjás"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #13" do
    cyr = "' ім’я 'жук' \"жук\" ' '"
    lat = "' im'ja 'zhuk' \"zhuk\" ' '"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #14" do
    cyr =
      "Сонце світить майже білим світлом, однак через сильніше розсіювання і поглинання короткохвильової частини спектра атмосферою Землі пряме світло Сонця біля поверхні нашої планети набуває певного жовтого відтінку. Якщо небо ясне, то блакитний відтінок розсіяного світла складається з жовтуватим прямим сонячним світлом і загальне освітлення об’єктів на Землі стає білим."

    lat =
      "Sonce svitytj majzhe bilym svitlom, odnak cherez syljnishe rozsijuvannja i poghlynannja korotkokhvyljovoji chastyny spektra atmosferoju Zemli prjame svitlo Soncja bilja poverkhni nashoji planety nabuvaje pevnogho zhovtogho vidtinku. Jakshcho nebo jasne, to blakytnyj vidtinok rozsijanogho svitla skladajetjsja z zhovtuvatym prjamym sonjachnym svitlom i zaghaljne osvitlennja ob'jektiv na Zemli staje bilym."

    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #20" do
    cyr =
      "дуб!дуб\"дуб#дуб$дуб%дуб&дуб'дуб(дуб)дуб*дуб+дуб,дуб-дуб.дуб/дуб:дуб;дуб<дуб=дуб>дуб?дуб@дуб[дуб\\дуб]дуб^дуб_дуб`дуб{дуб|дуб}дуб~дуб"

    lat =
      "dub!dub\"dub#dub$dub%dub&dub'dub(dub)dub*dub+dub,dub-dub.dub/dub:dub;dub<dub=dub>dub?dub@dub[dub\\dub]dub^dub_dub`dub{dub|dub}dub~dub"

    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #21" do
    cyr = "бод бод\tбод\nбод\rбод"
    lat = "bod bod\tbod\nbod\rbod"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #22" do
    cyr = "об😎нап😘неп😭нєп🧐нїп😍нюп😀няп"
    lat = "ob😎nap😘nep😭njep🧐njip😍njup😀njap"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #15" do
    cyr = "в’я в'я"
    lat = "v'ja v'ja"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
  end

  test "DSTU_9112_B #16" do
    cyr = "Ї ї Й й Ё ё Ў ў"
    lat = "JI ji J j JOW jow UH uh"
    assert Paiv.UkrainianLatin.encode(cyr, :DSTU_9112_B) == lat
  end

  test "DSTU_9112_B #17" do
    cyr = "я ї є ю г ж х щ ш ч ь"
    lat = "jA jI jE jU gH zH kH sHcH sH cH hJ"
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #18" do
    cyr = "А́ а́ Е́ е́ Є́ Є́ є́ є́ И́ и́ І́ і́ Ї́ Ї́ ї́ ї́ О́ о́ У́ у́ Ю́ Ю́ ю́ ю́ Я́ Я́ я́ я́"
    lat = "Á á É é JÉ Jé jÉ jé Ý ý Í í JÍ Jí jÍ jí Ó ó Ú ú JÚ Jú jÚ jú JÁ Já jÁ já"
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "DSTU_9112_B #19" do
    cyr = "Є́с сЄ́с є́с сє́с Ї́с сЇ́с ї́с сї́с Ю́с сЮ́с ю́с сю́с Я́с сЯ́с я́с ся́с"
    lat = "Jés sJés jés sjés Jís sJís jís sjís Jús sJús jús sjús Jás sJás jás sjás"
    assert Paiv.UkrainianLatin.decode(lat, :DSTU_9112_B) == cyr
  end

  test "KMU_55 #1" do
    cyr = "Україна, Хмельницький"
    lat = "Ukraina, Khmelnytskyi"
    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end

  test "KMU_55 #2" do
    cyr = "Щастям б’єш жук їх глицю в фон й ґедзь пріч."
    lat = "Shchastiam biesh zhuk yikh hlytsiu v fon y gedz prich."
    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end

  test "KMU_55 #3" do
    cyr = "згин зГ зГин Згин Зг ЗГ ЗГИН"
    lat = "zghyn zGH zGhyn Zghyn Zgh ZGH ZGHYN"
    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end

  test "KMU_55 #4" do
    cyr = "ь Ь ль льє льї лью лья лье льі льу льа льйо льо"
    lat = "  l lie li liu lia le li lu la lio lo"
    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end

  test "KMU_55 #5" do
    cyr = "Єл Їл Юл Ял"
    lat = "Yel Yil Yul Yal"
    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end

  test "KMU_55 #6" do
    cyr = "бь вь гь ґь дь жь зь кь ль мь нь пь рь сь ть фь хь ць чь шь щь"
    lat = "b v h g d zh z k l m n p r s t f kh ts ch sh shch"
    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end

  test "KMU_55 #7" do
    cyr = "бя вя гя ґя дя жя зя кя ля мя ня пя ря ся тя фя хя ця чя шя щя"

    lat =
      "bia via hia gia dia zhia zia kia lia mia nia pia ria sia tia fia khia tsia chia shia shchia"

    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end

  test "KMU_55 #8" do
    cyr = "б’я в’я г’я ґ’я д’я ж’я з’я к’я л’я м’я н’я п’я р’я с’я т’я ф’я х’я ц’я ч’я ш’я щ’я"

    lat =
      "bia via hia gia dia zhia zia kia lia mia nia pia ria sia tia fia khia tsia chia shia shchia"

    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end

  test "KMU_55 #9" do
    cyr = "бй бйо вй гй ґй дй жй зй кй лй мй нй пй рй сй тй фй хй цй чй шй щй"
    lat = "bi bio vi hi gi di zhi zi ki li mi ni pi ri si ti fi khi tsi chi shi shchi"
    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end

  test "KMU_55 #10" do
    cyr = "А́ а́ Е́ е́ Є́ є́ И́ и́ І́ і́ Ї́ ї́ О́ о́ У́ у́ Ю́ ю́ Я́ я́"
    lat = "Á á É é YÉ yé Ý ý Í í YÍ yí Ó ó Ú ú YÚ yú YÁ yá"
    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end

  test "KMU_55 #11" do
    cyr = "Є́с сЄ́с є́с сє́с Ї́с сЇ́с ї́с сї́с Ю́с сЮ́с ю́с сю́с Я́с сЯ́с я́с ся́с"
    lat = "Yés sIés yés siés Yís sÍs yís sís Yús sIús yús siús Yás sIás yás siás"
    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end

  test "KMU_55 #12" do
    cyr = "' ім’я 'жук' \"жук\" ' '"
    lat = "' imia 'zhuk' \"zhuk\" ' '"
    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end

  test "KMU_55 #13" do
    cyr =
      "Сонце світить майже білим світлом, однак через сильніше розсіювання і поглинання короткохвильової частини спектра атмосферою Землі пряме світло Сонця біля поверхні нашої планети набуває певного жовтого відтінку. Якщо небо ясне, то блакитний відтінок розсіяного світла складається з жовтуватим прямим сонячним світлом і загальне освітлення об’єктів на Землі стає білим."

    lat =
      "Sontse svityt maizhe bilym svitlom, odnak cherez sylnishe rozsiiuvannia i pohlynannia korotkokhvylovoi chastyny spektra atmosferoiu Zemli priame svitlo Sontsia bilia poverkhni nashoi planety nabuvaie pevnoho zhovtoho vidtinku. Yakshcho nebo yasne, to blakytnyi vidtinok rozsiianoho svitla skladaietsia z zhovtuvatym priamym soniachnym svitlom i zahalne osvitlennia obiektiv na Zemli staie bilym."

    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end

  test "KMU_55 #14" do
    cyr = "в’я в'я"
    lat = "via via"
    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end

  test "KMU_55 #15" do
    cyr =
      "дуб!дуб\"дуб#дуб$дуб%дуб&дуб'дуб(дуб)дуб*дуб+дуб,дуб-дуб.дуб/дуб:дуб;дуб<дуб=дуб>дуб?дуб@дуб[дуб\\дуб]дуб^дуб_дуб`дуб{дуб|дуб}дуб~дуб"

    lat =
      "dub!dub\"dub#dub$dub%dub&dubdub(dub)dub*dub+dub,dub-dub.dub/dub:dub;dub<dub=dub>dub?dub@dub[dub\\dub]dub^dub_dub`dub{dub|dub}dub~dub"

    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end

  test "KMU_55 #16" do
    cyr = "бод бод\tбод\nбод\rбод"
    lat = "bod bod\tbod\nbod\rbod"
    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end

  test "KMU_55 #17" do
    cyr = "об😎нап😘неп😭нєп🧐нїп😍нюп😀няп"
    lat = "ob😎nap😘nep😭niep🧐nip😍niup😀niap"
    assert Paiv.UkrainianLatin.encode(cyr, :KMU_55) == lat
  end
end
