/* Generated by gentests.py, do not edit. */


static const struct _uklatn_test _cyr2lat2cyr_data[] = {
    {
        u"Україна, Хмельницький",
        u"Ukraïna, Xmeljnycjkyj",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"Щастям б’єш жук їх глицю в фон й ґедзь пріч.",
        u"Ŝastjam b'ješ žuk ïx ğlycju v fon j gedzj prič.",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"ь Ь ль льє льї лью лья лье льі льу льа льйо льо",
        u"ĵ Ĵ lj ljje ljï ljju ljja lj'e lji lj'u lj'a ljjo ljo",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"Єл Їл Юл Ял",
        u"Jel Ïl Jul Jal",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"бь вь гь ґь дь жь зь кь ль мь нь пь рь сь ть фь хь ць чь шь щь",
        u"bj vj ğj gj dj žj zj kj lj mj nj pj rj sj tj fj xj cj čj šj ŝj",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"бя вя гя ґя дя жя зя кя ля мя ня пя ря ся тя фя хя ця чя шя щя",
        u"bja vja ğja gja dja žja zja kja lja mja nja pja rja sja tja fja xja cja čja šja ŝja",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"б’я в’я г’я ґ’я д’я ж’я з’я к’я л’я м’я н’я п’я р’я с’я т’я ф’я х’я ц’я ч’я ш’я щ’я",
        u"b'ja v'ja ğ'ja g'ja d'ja ž'ja z'ja k'ja l'ja m'ja n'ja p'ja r'ja s'ja t'ja f'ja x'ja c'ja č'ja š'ja ŝ'ja",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"бй бйо вй гй ґй дй жй зй кй лй мй нй пй рй сй тй фй хй цй чй шй щй",
        u"b'j b'jo v'j ğ'j g'j d'j ž'j z'j k'j l'j m'j n'j p'j r'j s'j t'j f'j x'j c'j č'j š'j ŝ'j",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"ня ньа н’я нь'н ньн",
        u"nja nj'a n'ja nj'n njn",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"рос дыня эзёдынъ. бр кроў.",
        u"ros dȳnja ēzödȳnǒ. br kroŭ.",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"А́ а́ Е́ е́ Є́ є́ И́ и́ І́ і́ Ї́ ї́ О́ о́ У́ у́ Ю́ ю́ Я́ я́",
        u"Á á É é JÉ jé Ý ý Í í Ḯ ḯ Ó ó Ú ú JÚ jú JÁ já",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"Є́с сЄ́с є́с сє́с Ї́с сЇ́с ї́с сї́с Ю́с сЮ́с ю́с сю́с Я́с сЯ́с я́с ся́с",
        u"Jés sJés jés sjés Ḯs sḮs ḯs sḯs Jús sJús jús sjús Jás sJás jás sjás",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"' ім’я 'жук' \"жук\" ' '",
        u"' im'ja 'žuk' \"žuk\" ' '",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"Сонце світить майже білим світлом, однак через сильніше розсіювання і поглинання короткохвильової частини спектра атмосферою Землі пряме світло Сонця біля поверхні нашої планети набуває певного жовтого відтінку. Якщо небо ясне, то блакитний відтінок розсіяного світла складається з жовтуватим прямим сонячним світлом і загальне освітлення об’єктів на Землі стає білим.",
        u"Sonce svitytj majže bilym svitlom, odnak čerez syljniše rozsijuvannja i poğlynannja korotkoxvyljovoï častyny spektra atmosferoju Zemli prjame svitlo Soncja bilja poverxni našoï planety nabuvaje pevnoğo žovtoğo vidtinku. Jakŝo nebo jasne, to blakytnyj vidtinok rozsijanoğo svitla skladajetjsja z žovtuvatym prjamym sonjačnym svitlom i zağaljne osvitlennja ob'jektiv na Zemli staje bilym.",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"дуб!дуб\"дуб#дуб$дуб%дуб&дуб'дуб(дуб)дуб*дуб+дуб,дуб-дуб.дуб/дуб:дуб;дуб<дуб=дуб>дуб?дуб@дуб[дуб\\дуб]дуб^дуб_дуб`дуб{дуб|дуб}дуб~дуб",
        u"dub!dub\"dub#dub$dub%dub&dub'dub(dub)dub*dub+dub,dub-dub.dub/dub:dub;dub<dub=dub>dub?dub@dub[dub\\dub]dub^dub_dub`dub{dub|dub}dub~dub",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"бод бод\tбод\nбод\rбод",
        u"bod bod\tbod\nbod\rbod",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"об😎нап😘неп😭нєп🧐нїп😍нюп😀няп",
        u"ob😎nap😘nep😭njep🧐nïp😍njup😀njap",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"Україна, Хмельницький",
        u"Ukrajina, Khmeljnycjkyj",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"Щастям б’єш жук їх глицю в фон й ґедзь пріч.",
        u"Shchastjam b'jesh zhuk jikh ghlycju v fon j gedzj prich.",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"ь Ь ль льє льї лью лья лье льі льу льа льйо льо",
        u"hj Hj lj ljje ljji ljju ljja lj'e lj'i lj'u lj'a ljjo ljo",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"Єл Їл Юл Ял",
        u"Jel Jil Jul Jal",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"бь вь гь ґь дь жь зь кь ль мь нь пь рь сь ть фь хь ць чь шь щь",
        u"bj vj ghj gj dj zhj zj kj lj mj nj pj rj sj tj fj khj cj chj shj shchj",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"бя вя гя ґя дя жя зя кя ля мя ня пя ря ся тя фя хя ця чя шя щя",
        u"bja vja ghja gja dja zhja zja kja lja mja nja pja rja sja tja fja khja cja chja shja shchja",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"б’я в’я г’я ґ’я д’я ж’я з’я к’я л’я м’я н’я п’я р’я с’я т’я ф’я х’я ц’я ч’я ш’я щ’я",
        u"b'ja v'ja gh'ja g'ja d'ja zh'ja z'ja k'ja l'ja m'ja n'ja p'ja r'ja s'ja t'ja f'ja kh'ja c'ja ch'ja sh'ja shch'ja",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"бй бйо вй гй ґй дй жй зй кй лй мй нй пй рй сй тй фй хй цй чй шй щй",
        u"b'j b'jo v'j gh'j g'j d'j zh'j z'j k'j l'j m'j n'j p'j r'j s'j t'j f'j kh'j c'j ch'j sh'j shch'j",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"ня ньа н’я нь'н ньн",
        u"nja nj'a n'ja nj'n njn",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"рос дыня эзёдынъ. бр кроў.",
        u"ros dywnja ehwzjowdywnoh. br krouh.",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"А́ а́ Е́ е́ Є́ є́ И́ и́ І́ і́ Ї́ ї́ О́ о́ У́ у́ Ю́ ю́ Я́ я́",
        u"Á á É é JÉ jé Ý ý Í í JÍ jí Ó ó Ú ú JÚ jú JÁ já",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"Є́с сЄ́с є́с сє́с Ї́с сЇ́с ї́с сї́с Ю́с сЮ́с ю́с сю́с Я́с сЯ́с я́с ся́с",
        u"Jés sJés jés sjés Jís sJís jís sjís Jús sJús jús sjús Jás sJás jás sjás",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"' ім’я 'жук' \"жук\" ' '",
        u"' im'ja 'zhuk' \"zhuk\" ' '",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"Сонце світить майже білим світлом, однак через сильніше розсіювання і поглинання короткохвильової частини спектра атмосферою Землі пряме світло Сонця біля поверхні нашої планети набуває певного жовтого відтінку. Якщо небо ясне, то блакитний відтінок розсіяного світла складається з жовтуватим прямим сонячним світлом і загальне освітлення об’єктів на Землі стає білим.",
        u"Sonce svitytj majzhe bilym svitlom, odnak cherez syljnishe rozsijuvannja i poghlynannja korotkokhvyljovoji chastyny spektra atmosferoju Zemli prjame svitlo Soncja bilja poverkhni nashoji planety nabuvaje pevnogho zhovtogho vidtinku. Jakshcho nebo jasne, to blakytnyj vidtinok rozsijanogho svitla skladajetjsja z zhovtuvatym prjamym sonjachnym svitlom i zaghaljne osvitlennja ob'jektiv na Zemli staje bilym.",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"дуб!дуб\"дуб#дуб$дуб%дуб&дуб'дуб(дуб)дуб*дуб+дуб,дуб-дуб.дуб/дуб:дуб;дуб<дуб=дуб>дуб?дуб@дуб[дуб\\дуб]дуб^дуб_дуб`дуб{дуб|дуб}дуб~дуб",
        u"dub!dub\"dub#dub$dub%dub&dub'dub(dub)dub*dub+dub,dub-dub.dub/dub:dub;dub<dub=dub>dub?dub@dub[dub\\dub]dub^dub_dub`dub{dub|dub}dub~dub",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"бод бод\tбод\nбод\rбод",
        u"bod bod\tbod\nbod\rbod",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"об😎нап😘неп😭нєп🧐нїп😍нюп😀няп",
        u"ob😎nap😘nep😭njep🧐njip😍njup😀njap",
        UklatnTable_DSTU_9112_B,
    },
};

static const struct _uklatn_test _lat2cyr2lat_data[] = {
};

static const struct _uklatn_test _cyr2lat_data[] = {
    {
        u"в’я в'я",
        u"v'ja v'ja",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"Ї ї Й й Ё ё Ў ў",
        u"Ï ï J j Ö ö Ŭ ŭ",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"в’я в'я",
        u"v'ja v'ja",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"Ї ї Й й Ё ё Ў ў",
        u"JI ji J j JOW jow UH uh",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"Україна, Хмельницький",
        u"Ukraina, Khmelnytskyi",
        UklatnTable_KMU_55,
    },
    {
        u"Щастям б’єш жук їх глицю в фон й ґедзь пріч.",
        u"Shchastiam biesh zhuk yikh hlytsiu v fon y gedz prich.",
        UklatnTable_KMU_55,
    },
    {
        u"згин зГ зГин Згин Зг ЗГ ЗГИН",
        u"zghyn zGH zGhyn Zghyn Zgh ZGH ZGHYN",
        UklatnTable_KMU_55,
    },
    {
        u"ь Ь ль льє льї лью лья лье льі льу льа льйо льо",
        u"  l lie li liu lia le li lu la lio lo",
        UklatnTable_KMU_55,
    },
    {
        u"Єл Їл Юл Ял",
        u"Yel Yil Yul Yal",
        UklatnTable_KMU_55,
    },
    {
        u"бь вь гь ґь дь жь зь кь ль мь нь пь рь сь ть фь хь ць чь шь щь",
        u"b v h g d zh z k l m n p r s t f kh ts ch sh shch",
        UklatnTable_KMU_55,
    },
    {
        u"бя вя гя ґя дя жя зя кя ля мя ня пя ря ся тя фя хя ця чя шя щя",
        u"bia via hia gia dia zhia zia kia lia mia nia pia ria sia tia fia khia tsia chia shia shchia",
        UklatnTable_KMU_55,
    },
    {
        u"б’я в’я г’я ґ’я д’я ж’я з’я к’я л’я м’я н’я п’я р’я с’я т’я ф’я х’я ц’я ч’я ш’я щ’я",
        u"bia via hia gia dia zhia zia kia lia mia nia pia ria sia tia fia khia tsia chia shia shchia",
        UklatnTable_KMU_55,
    },
    {
        u"бй бйо вй гй ґй дй жй зй кй лй мй нй пй рй сй тй фй хй цй чй шй щй",
        u"bi bio vi hi gi di zhi zi ki li mi ni pi ri si ti fi khi tsi chi shi shchi",
        UklatnTable_KMU_55,
    },
    {
        u"А́ а́ Е́ е́ Є́ є́ И́ и́ І́ і́ Ї́ ї́ О́ о́ У́ у́ Ю́ ю́ Я́ я́",
        u"Á á É é YÉ yé Ý ý Í í YÍ yí Ó ó Ú ú YÚ yú YÁ yá",
        UklatnTable_KMU_55,
    },
    {
        u"Є́с сЄ́с є́с сє́с Ї́с сЇ́с ї́с сї́с Ю́с сЮ́с ю́с сю́с Я́с сЯ́с я́с ся́с",
        u"Yés sIés yés siés Yís sÍs yís sís Yús sIús yús siús Yás sIás yás siás",
        UklatnTable_KMU_55,
    },
    {
        u"' ім’я 'жук' \"жук\" ' '",
        u"' imia 'zhuk' \"zhuk\" ' '",
        UklatnTable_KMU_55,
    },
    {
        u"Сонце світить майже білим світлом, однак через сильніше розсіювання і поглинання короткохвильової частини спектра атмосферою Землі пряме світло Сонця біля поверхні нашої планети набуває певного жовтого відтінку. Якщо небо ясне, то блакитний відтінок розсіяного світла складається з жовтуватим прямим сонячним світлом і загальне освітлення об’єктів на Землі стає білим.",
        u"Sontse svityt maizhe bilym svitlom, odnak cherez sylnishe rozsiiuvannia i pohlynannia korotkokhvylovoi chastyny spektra atmosferoiu Zemli priame svitlo Sontsia bilia poverkhni nashoi planety nabuvaie pevnoho zhovtoho vidtinku. Yakshcho nebo yasne, to blakytnyi vidtinok rozsiianoho svitla skladaietsia z zhovtuvatym priamym soniachnym svitlom i zahalne osvitlennia obiektiv na Zemli staie bilym.",
        UklatnTable_KMU_55,
    },
    {
        u"в’я в'я",
        u"via via",
        UklatnTable_KMU_55,
    },
    {
        u"дуб!дуб\"дуб#дуб$дуб%дуб&дуб'дуб(дуб)дуб*дуб+дуб,дуб-дуб.дуб/дуб:дуб;дуб<дуб=дуб>дуб?дуб@дуб[дуб\\дуб]дуб^дуб_дуб`дуб{дуб|дуб}дуб~дуб",
        u"dub!dub\"dub#dub$dub%dub&dubdub(dub)dub*dub+dub,dub-dub.dub/dub:dub;dub<dub=dub>dub?dub@dub[dub\\dub]dub^dub_dub`dub{dub|dub}dub~dub",
        UklatnTable_KMU_55,
    },
    {
        u"бод бод\tбод\nбод\rбод",
        u"bod bod\tbod\nbod\rbod",
        UklatnTable_KMU_55,
    },
    {
        u"об😎нап😘неп😭нєп🧐нїп😍нюп😀няп",
        u"ob😎nap😘nep😭niep🧐nip😍niup😀niap",
        UklatnTable_KMU_55,
    },
};

static const struct _uklatn_test _lat2cyr_data[] = {
    {
        u"я є ю",
        u"jA jE jU",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"Ї ї Ь ь Ч ч Г г Щ щ Ш ш Ж ж",
        u"Ï ï Ĵ ĵ Č č Ğ ğ Ŝ ŝ Š š Ž ž",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"Ё ё Ў ў Ъ ъ Ы ы Э э",
        u"Ö ö Ŭ ŭ Ǒ ǒ Ȳ ȳ Ē ē",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"А́ а́ Е́ е́ Є́ Є́ є́ є́ И́ и́ І́ і́ Ї́ ї́ О́ о́ У́ у́ Ю́ Ю́ ю́ ю́ Я́ Я́ я́ я́",
        u"Á á É é JÉ Jé jÉ jé Ý ý Í í Ḯ ḯ Ó ó Ú ú JÚ Jú jÚ jú JÁ Já jÁ já",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"Є́с сЄ́с є́с сє́с Ї́с сЇ́с ї́с сї́с Ю́с сЮ́с ю́с сю́с Я́с сЯ́с я́с ся́с",
        u"Jés sJés jés sjés Ḯs sḮs ḯs sḯs Jús sJús jús sjús Jás sJás jás sjás",
        UklatnTable_DSTU_9112_A,
    },
    {
        u"я ї є ю г ж х щ ш ч ь",
        u"jA jI jE jU gH zH kH sHcH sH cH hJ",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"А́ а́ Е́ е́ Є́ Є́ є́ є́ И́ и́ І́ і́ Ї́ Ї́ ї́ ї́ О́ о́ У́ у́ Ю́ Ю́ ю́ ю́ Я́ Я́ я́ я́",
        u"Á á É é JÉ Jé jÉ jé Ý ý Í í JÍ Jí jÍ jí Ó ó Ú ú JÚ Jú jÚ jú JÁ Já jÁ já",
        UklatnTable_DSTU_9112_B,
    },
    {
        u"Є́с сЄ́с є́с сє́с Ї́с сЇ́с ї́с сї́с Ю́с сЮ́с ю́с сю́с Я́с сЯ́с я́с ся́с",
        u"Jés sJés jés sjés Jís sJís jís sjís Jús sJús jús sjús Jás sJás jás sjás",
        UklatnTable_DSTU_9112_B,
    },
};
