name: Python

on:
  push:
    tags:
    - '*'
    - '!go/*'
  pull_request:
    branches: [main]
    paths:
    - 'python/**/*'
    - 'pyproject.toml'
    - 'MANIFEST.in'

jobs:

  build-py:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test
      working-directory: ${{github.workspace}}/python
      run: make test

    - name: Test CLI
      working-directory: ${{github.workspace}}/python
      run: |
        sh -c '[ "$(python uklatn.py -t DSTU_9112_B мрії мої)" = "mriji moji" ]'

    - name: Test CLI pipe
      working-directory: ${{github.workspace}}/python
      run: |
        sh -c '[ "$(echo мрії мої | python uklatn.py -t DSTU_9112_B -f -)" = "mriji moji" ]'
