name: Ruby

on:
  push:
    tags: ['*']
  pull_request:
    branches: [main]
    paths:
    - 'ruby/**/*'
    - 'uklatn.gemspec'

jobs:

  build-py:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test
      working-directory: ${{github.workspace}}/ruby
      run: make test
