name: Java

on:
  push:
    tags:
    - '[0-9]**'
  pull_request:
    branches: [main]
    paths:
    - 'java/**'
    - '.github/workflows/build-java.yml'

jobs:

  build-java:
    strategy:
      matrix:
        java_version: [11, 21]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java_version}}

    - name: Version
      run: mvn --version

    - name: Test
      working-directory: ${{github.workspace}}/java
      run: mvn -q test
