name: Swift

on:
  push:
    tags:
    - '*'
    - '!go/*'
  pull_request:
    branches: [main]
    paths:
    - 'swift/**/*.swift'
    - 'Package.swift'

jobs:

  build-swift:
    name: Swift ${{matrix.platform}} ${{matrix.build_type}}
    strategy:
      matrix:
        build_type: [debug, release]
        platform: [macos-latest, ubuntu-latest]

    runs-on: ${{matrix.platform}}

    steps:
    - uses: actions/checkout@v4

    - name: Swift version
      run: swift -version

    - name: Build
      run: swift build -c ${{matrix.build_type}}

    - name: Test
      run: swift test -c ${{matrix.build_type}}

    - name: Test CLI
      run: |
        sh -c '[ "$(swift run uklatn -t DSTU_9112_B мрії мої)" = "mriji moji" ]'

    - name: Test CLI pipe
      run: |
        sh -c '[ "$(echo мрії мої | swift run uklatn -t DSTU_9112_B -f -)" = "mriji moji" ]'
