name: .NET C#

on:
  push:
    tags:
    - '[0-9]**'
  pull_request:
    branches: [main]
    paths:
    - 'csharp/**'
    - '.github/workflows/build-csharp.yml'

jobs:

  build-csharp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6

    - name: .NET version
      run: dotnet --info

    - name: Test
      working-directory: ${{github.workspace}}/csharp
      run: dotnet test
