name: C library

on:
  push:
    tags:
    - '[0-9]**'
  pull_request:
    branches: [main]
    paths:
    - 'c/**'
    - 'CMakeLists.txt'

env:
  LIBICU: libicu70

jobs:

  build-c:
    strategy:
      matrix:
        BUILD_TYPE: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install ICU
      run: |
        # sudo apt-get update -y
        sudo apt-get install -y libicu-dev ${{env.LIBICU}}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.BUILD_TYPE}}
