name: Build

on:
  pull_request:
    branches: [main]
  push:
    tags: ['*']

env:
  LIBICU: libicu70

jobs:

  build-c:
    strategy:
      matrix:
        BUILD_TYPE: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install ICU
      run: |
        # sudo apt-get update -y
        sudo apt-get install -y libicu-dev ${{env.LIBICU}}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.BUILD_TYPE}}


  build-js:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test
      run: npm test

    - name: Install
      run: |
        npm install --global

    - name: Test CLI
      run: |
        sh -c '[ "$(npm exec -- uklatn -t DSTU_9112_B мрії мої)" = "mriji moji" ]'

    - name: Test CLI pipe
      run: |
        sh -c '[ "$(echo мрії мої | npm exec -- uklatn -t DSTU_9112_B -f -)" = "mriji moji" ]'


  build-py:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test
      working-directory: ${{github.workspace}}/python
      run: make test

    - name: Test CLI
      working-directory: ${{github.workspace}}/python
      run: |
        sh -c '[ "$(python uklatn.py -t DSTU_9112_B мрії мої)" = "mriji moji" ]'

    - name: Test CLI pipe
      working-directory: ${{github.workspace}}/python
      run: |
        sh -c '[ "$(echo мрії мої | python uklatn.py -t DSTU_9112_B -f -)" = "mriji moji" ]'


  build-swift:
    name: Swift ${{matrix.platform}} ${{matrix.build_type}}
    strategy:
      matrix:
        build_type: [debug, release]
        platform: [macos-latest, ubuntu-latest]

    runs-on: ${{matrix.platform}}

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: swift build -c ${{matrix.build_type}}

    - name: Test
      run: swift test -c ${{matrix.build_type}}

